### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NoName7258** [Kayn277/tgbot#1]
Traceback (most recent call last):
  File "RunBots.py", line 300, in <module>
    connect = psycopg2.connect(dbname='parsedaccounts', user='postgres',
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Отдыхаем 60 секунд

Помоги пожалуйста

**Comment by Kayn277** [comment]
Нужно установить PostgreSQL

**Comment by Kayn277** [comment]
https://khashtamov.com/ru/postgresql-python-psycopg2 Можешь почитать о работе с PostgreSQL

**Comment by Kayn277** [comment]
Когда будет время допишу код который автоматически будет генерировать полную таблицу, но пока без нее, т.к. писал для себя. Так что это как ознакомительный код. Выложу дамп бд, чтобы можно было экспортировать ее в свою субд

**Comment by Kayn277** [comment]
Добавил дамп. Надо установить Postgresql создать бд parsedaccounts и восстановить таблицы с помощью dbdump.sql
